version: '3.6'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: 'gitlab'
    hostname: 'gitlab.eth.su'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.eth.su'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['smtp_enable'] = true
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
  exim:
    image: tianon/exim4
    restart: always
    container_name: 'exim'
    hostname: 'gitlab.eth.su'
    ports:
      - '25:25'
 
