version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: 'gitlab'
    hostname: 'gitlab.eth.su'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.eth.su'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        # smtp settings documentation available here https://docs.gitlab.com/omnibus/settings/smtp.html
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'exim'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = 'exim'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$GITLAB_HOME/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab
  exim:
    image: tianon/exim4
    restart: always
    container_name: 'exim'
    hostname: 'gitlab.eth.su'
    ports:
      - '2525:25'
    networks:
      - gitlab
networks:
  gitlab:
    name: gitlab-network
